### ISSUE TITLE
Design mockups

### ISSUE THREAD

**Issue by juancoob** [Architect-Coders-Team-2/ArquitectoMarvel#1]
Create the mockups to know what the app is going to show

**Comment by jujoru** [comment]
Attached fluid UI URL with the first mockup mockup sketch.

[Ver mockup ](https://www.fluidui.com/editor/live/preview/cF9IVlJCVFR0bEZkZzUxd0RUZnM0ejNoUnNLRDdLWmhDRw==)

**Comment by juancoob** [comment]
Cool, it seems Fluidui is awesome :+1:
